### ISSUE TITLE
Release version 0.4.0 to PyPI

### ISSUE THREAD

**Issue by ipartola** [signed0/tabby#6]
Currently, the version on PyPI is 0.3.0. Can you release version 0.4.0, including your signature and a wheel package? Thanks!

**Comment by signed0** [comment]
I'll look at it when I get a chance.

**Comment by zipho** [comment]
Was this ever looked into..? The version in PyPI is still 0.3.0.

**Comment by signed0** [comment]
I don't think I ever got around to it. If you're using this I'll happily do so. Do you need Python 2 support or Python 3?

**Comment by zipho** [comment]
Pytho 3 support. Thanks @signed0

**Comment by signed0** [comment]
Just uploaded it to PyPi. Sorry for the delay! Please let me know if you have any issues with it.
